name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build Rust Project
      run: cargo build --release

    - name: Compile Inno Setup Installer
      run: iscc installer.iss

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StellarisMapQuery-Installer
        path: Output/StellarisMapQuery_Setup.exe